services:
  server:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '${PORT:-4000}:${PORT:-4000}'
